// Generated by ts-to-zod
import { z } from "zod";

export const vADStateSchema = z.object({
  valence: z.number(),
  arousal: z.number(),
  dominance: z.number(),
});

export const timestampSchema = z.object({
  created_at: z.string(),
  last_updated: z.string(),
});

export const accessMetricsSchema = z.object({
  last_accessed: z.string(),
  access_count: z.number(),
});

export const importanceScoreSchema = z.object({
  importance_score: z.number(),
});

export const weightedMemoryFusionSchema = z.object({
  w_L1: z.number(),
  w_L2: z.number(),
  w_L3: z.number(),
});

export const tokenCostSchema = z.object({
  total_tokens: z.number(),
  l1_tokens: z.number(),
  l2_tokens: z.number(),
  l3_tokens: z.number(),
  estimated_cost: z.number(),
});
